### PR TITLE
Setup basic doxygen configuration

### PR DESCRIPTION
**Pull request by slfuchs**
This pull request sets up the basic doxygen configuration.

### CODE REVIEW

**Comment by slfuchs** [comment]
@peterrum: I am currently working on setting up a GitHub workflow to build and deploy the doxygen documentation based on your approach in [hyper.deal](https://github.com/hyperdeal/hyperdeal). However, my goal is to deploy the documentation in a separate repository called for example PartExa/doxygen. This should be straightforward as far as I have seen.

**Comment by peterrum** [comment]
See: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository

**Comment by ppraegla** [comment]
@slfuchs The deployment of the doxygen files to another repo will be a follow-up PR, right?

**Comment by slfuchs** [comment]
Yes, I'd like to merge this PR. The basic doxygen configuration is included and one can locally build it via `make doxygen`. In a follow-up PR I want to set up the GitHub workflow to generate and deploy the documentation.

Both PR can than serve as a starting point for adding the Sphinx documentation (that includes installation and build instructions of PartExa and many more).

**Review by ppraegla — APPROVED** [review]

**Pull request merged**
