### PR TITLE
Add separate deploy job for doxygen GitHub action

### PR DESCRIPTION
**Pull request by slfuchs**
This pull requests adds a separate deploy job for the doxygen GitHub action.

### CODE REVIEW

**Review by peterrum — APPROVED** [review]
This was what I said in https://github.com/PartExa/PartExa/pull/14#discussion_r769086091 but did not how to do ;)

**Comment by slfuchs** [comment]
Using the artifact action is quite simple. We can also access the `doxygen` artifact from the actions page, e.g., here https://github.com/PartExa/PartExa/actions/runs/1583372553, if needed.

**Comment by slfuchs** [comment]
Okay, let's give it a try. All deploy keys are set.

**Comment by slfuchs** [comment]
Yessss! No that it is finally working, I will write a short summary of all important steps in an issue. Such that we are faster when adding a Sphinx documentation in a next step.

**Pull request merged**
