### PR TITLE
Fix doxygen GitHub action

### PR DESCRIPTION
**Pull request by slfuchs**
Fix the failing workflow https://github.com/PartExa/PartExa/runs/4522338030?check_suite_focus=true.
Observed error in the `Deploy` step:
```
Run peaceiris/actions-gh-pages@v3
/usr/bin/docker exec  84b79d2eae4e909fef0b64fc4b57e9bf9a9d3686d3d20921a1a6a36327f4023c sh -c "cat /etc/*release | grep ^ID"
[INFO] Usage https://github.com/peaceiris/actions-gh-pages#readme
Dump inputs
Setup auth token
  [INFO] setup SSH deploy key
  Error: Action failed with "EACCES: permission denied, mkdir '/github/home/.ssh'"
```
Setting the owner of the directory $HOME (`/github/home`) should fix the problem. An alternative would have been to run the container with `options: --user root`.

Following #11

### CODE REVIEW

**Review by peterrum — APPROVED** [review]
Want to merge if it helps!?

**Comment by slfuchs** [comment]
@peterrum Thanks for the fast reaction, yes, let's merge and hope for the best.

**Comment by peterrum** [comment]
No success. `/__w/...` is an issue inside of the Docker image. Question: why are you building the documentation within the deal.II docker image? I would simply run Docker plain - not indirectly cmake.

**Comment by slfuchs** [comment]
There are multiple reason:
- I want to run the same configuration and generation steps of doxygen that a user would also do locally
- this also allows us to test for errors in the file `doxygen.err`
- the Doxyfile.in in also processed by cmake

**Comment by peterrum** [comment]
I understand that part. But deploying does not need it. Why not split it up
```
jobs:
  check-docu:
    runs-on: ubuntu-latest
    
    container:
      image: dealii/dealii:master-focal

  deploy-docu:
    runs-on: ubuntu-latest
```

`deploy-docu` should run successfully (on master), since `check-docu` has been run already on the PR.

**Comment by slfuchs** [comment]
Ah okay, so we have access to the generated doxygen html directory also outside the deal.ii docker?

**Comment by peterrum** [comment]
Yes. But maybe there are other solutions. You mentioned somewhere something related root rights. Did you try that?

**Comment by slfuchs** [comment]
Yes, that's part of #13. But I think we should try your suggestion first. I am preparing a new PR.

**Pull request merged**
